package sk.stu.fiit.views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import sk.stu.fiit.controllers.DateTimeController;
import sk.stu.fiit.controllers.DownloadController;
import sk.stu.fiit.controllers.RecordController;
import sk.stu.fiit.exceptions.InvalidUrlException;
import sk.stu.fiit.exceptions.NoFileSelected;
import sk.stu.fiit.exceptions.NotZipException;
import sk.stu.fiit.utils.DestinationResolver;

/**
 *
 * @author Admin
 */
public final class MainView extends javax.swing.JFrame{

    private JLabel lblActualPanel;
    private final RecordController recordController;
    private final DownloadController downloadController;

    /**
     * Creates new form InitView
     */
    public MainView() {
        initComponents();     
        this.lblActualPanel = lblMain_main;
        this.downloadController = new DownloadController(this);
        this.recordController = new RecordController();
        recordController.setUpView(this);
        startInitingTables();
        updateTables();
        initWindowlistener();
    }
    
    public void startInitingTables(){
        DateTimeController.countDateAndTime(lblDate_main, lblTime_main, this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain_main = new javax.swing.JLabel();
        lblNewDownload_main = new javax.swing.JLabel();
        lblManageDownloads_main = new javax.swing.JLabel();
        lblUnzip_main = new javax.swing.JLabel();
        lblHistory_main = new javax.swing.JLabel();
        lblTopSplit = new javax.swing.JLabel();
        lblTopPanel = new javax.swing.JLabel();
        lblStatus_main = new javax.swing.JLabel();
        fldStatus = new javax.swing.JTextField();
        lblTime_main = new javax.swing.JLabel();
        lblDate_main = new javax.swing.JLabel();
        lblBottomSplit = new javax.swing.JLabel();
        lblBottomPanel = new javax.swing.JLabel();
        tabbs = new javax.swing.JTabbedPane();
        pnlMainPageP1 = new javax.swing.JPanel();
        lblMainTitleP1 = new javax.swing.JLabel();
        lblRecentDownloadsP1 = new javax.swing.JLabel();
        btnDetailP1 = new javax.swing.JButton();
        scrollP1 = new javax.swing.JScrollPane();
        tblDownloadsP1 = new javax.swing.JTable();
        lblNameP1 = new javax.swing.JLabel();
        fldNameP1 = new javax.swing.JTextField();
        fldSubjectP1 = new javax.swing.JTextField();
        lblSubjectP1 = new javax.swing.JLabel();
        fldCreatorsP1 = new javax.swing.JTextField();
        lblLanguageP1 = new javax.swing.JLabel();
        btnSlovakP1 = new javax.swing.JButton();
        btnEnglishP1 = new javax.swing.JButton();
        lblCreatorsP1 = new javax.swing.JLabel();
        btnOpenP1 = new javax.swing.JButton();
        lblBackgroundP1 = new javax.swing.JLabel();
        pnlNewDownloadP2 = new javax.swing.JPanel();
        fldLocationP2 = new javax.swing.JTextField();
        fldURLP2 = new javax.swing.JTextField();
        btnChooseLocationP2 = new javax.swing.JButton();
        lblMainTitleP2 = new javax.swing.JLabel();
        lblDestination_P2 = new javax.swing.JLabel();
        lblSource_P2 = new javax.swing.JLabel();
        lblSpaceP2 = new javax.swing.JLabel();
        fldSpaceP2 = new javax.swing.JTextField();
        lblSizeP2 = new javax.swing.JLabel();
        fldSizeP2 = new javax.swing.JTextField();
        lblSeparator6 = new javax.swing.JLabel();
        btnDownloadP2 = new javax.swing.JButton();
        lblBackgroundP2 = new javax.swing.JLabel();
        pnlManageDownloadsP3 = new javax.swing.JPanel();
        lblSourceP3 = new javax.swing.JLabel();
        fldSourceP3 = new javax.swing.JTextField();
        lblPercentage_P3 = new javax.swing.JLabel();
        progressBarP3 = new javax.swing.JProgressBar();
        scrollP3 = new javax.swing.JScrollPane();
        tblDownloadsP3 = new javax.swing.JTable();
        btnPauseP3 = new javax.swing.JButton();
        btnResumeP3 = new javax.swing.JButton();
        btnAbortP3 = new javax.swing.JButton();
        lblMainTitleP3 = new javax.swing.JLabel();
        fldStartP3 = new javax.swing.JTextField();
        lblStartP3 = new javax.swing.JLabel();
        fldDurationP3 = new javax.swing.JTextField();
        lblDurationP3 = new javax.swing.JLabel();
        fldRemainingP3 = new javax.swing.JTextField();
        lblRemainingP3 = new javax.swing.JLabel();
        lblDestinationP3 = new javax.swing.JLabel();
        fldDestinationP3 = new javax.swing.JTextField();
        lblSizeP3 = new javax.swing.JLabel();
        fldSizeP3 = new javax.swing.JTextField();
        lblStatusP3 = new javax.swing.JLabel();
        fldStatusP3 = new javax.swing.JTextField();
        lblBackgroundP3 = new javax.swing.JLabel();
        pnlUnzipP4 = new javax.swing.JPanel();
        lblMainTitleP4 = new javax.swing.JLabel();
        btnUnzipP4 = new javax.swing.JButton();
        scrollP4 = new javax.swing.JScrollPane();
        tblDownloadsP4 = new javax.swing.JTable();
        lblBackgroundP4 = new javax.swing.JLabel();
        pnlHistoryP5 = new javax.swing.JPanel();
        lblMainTitleP5 = new javax.swing.JLabel();
        scrollP5 = new javax.swing.JScrollPane();
        tblDownloadsP5 = new javax.swing.JTable();
        btnDetailP5 = new javax.swing.JButton();
        lblBackgroundP5 = new javax.swing.JLabel();
        pnlDetailP6 = new javax.swing.JPanel();
        lblSourceP6 = new javax.swing.JLabel();
        lblNameP6 = new javax.swing.JLabel();
        lblSizeP6 = new javax.swing.JLabel();
        fldSizeP6 = new javax.swing.JTextField();
        fldNameP6 = new javax.swing.JTextField();
        fldSourceP6 = new javax.swing.JTextField();
        lblDateP6 = new javax.swing.JLabel();
        lblDurationP6 = new javax.swing.JLabel();
        fldDurationP6 = new javax.swing.JTextField();
        fldDateP6 = new javax.swing.JTextField();
        lblMainTitleP6 = new javax.swing.JLabel();
        fldStatusP6 = new javax.swing.JTextField();
        lblStatusP6 = new javax.swing.JLabel();
        btnOpenP6 = new javax.swing.JButton();
        lblBackgroundP6 = new javax.swing.JLabel();
        lblTempP6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Downloader v2"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMain_main.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMain_main.setForeground(new java.awt.Color(3, 1, 54));
        lblMain_main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMain_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/polygonsBackground.jpg"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sk/stu/fiit/views/Bundle"); // NOI18N
        lblMain_main.setText(bundle.getString("MainView.lblMain_main.text")); // NOI18N
        lblMain_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 245, 255), 3));
        lblMain_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMain_main.setIconTextGap(0);
        lblMain_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMain_mainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMain_mainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMain_mainMouseExited(evt);
            }
        });
        getContentPane().add(lblMain_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 40));

        lblNewDownload_main.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNewDownload_main.setForeground(new java.awt.Color(3, 1, 54));
        lblNewDownload_main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewDownload_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/polygonsBackground.jpg"))); // NOI18N
        lblNewDownload_main.setText(bundle.getString("MainView.lblNewDownload_main.text_1")); // NOI18N
        lblNewDownload_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
        lblNewDownload_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNewDownload_main.setIconTextGap(0);
        lblNewDownload_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewDownload_mainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewDownload_mainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewDownload_mainMouseExited(evt);
            }
        });
        getContentPane().add(lblNewDownload_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 40));

        lblManageDownloads_main.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblManageDownloads_main.setForeground(new java.awt.Color(3, 1, 54));
        lblManageDownloads_main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageDownloads_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/polygonsBackground.jpg"))); // NOI18N
        lblManageDownloads_main.setText(bundle.getString("MainView.lblManageDownloads_main.text_1")); // NOI18N
        lblManageDownloads_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
        lblManageDownloads_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblManageDownloads_main.setIconTextGap(0);
        lblManageDownloads_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageDownloads_mainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageDownloads_mainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageDownloads_mainMouseExited(evt);
            }
        });
        getContentPane().add(lblManageDownloads_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 190, 40));

        lblUnzip_main.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUnzip_main.setForeground(new java.awt.Color(3, 1, 54));
        lblUnzip_main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnzip_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/polygonsBackground.jpg"))); // NOI18N
        lblUnzip_main.setText(bundle.getString("MainView.lblUnzip_main.text_1")); // NOI18N
        lblUnzip_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
        lblUnzip_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUnzip_main.setIconTextGap(0);
        lblUnzip_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUnzip_mainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUnzip_mainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUnzip_mainMouseExited(evt);
            }
        });
        getContentPane().add(lblUnzip_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 120, 40));

        lblHistory_main.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHistory_main.setForeground(new java.awt.Color(3, 1, 54));
        lblHistory_main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistory_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/polygonsBackground.jpg"))); // NOI18N
        lblHistory_main.setText(bundle.getString("MainView.lblHistory_main.text_1")); // NOI18N
        lblHistory_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
        lblHistory_main.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHistory_main.setIconTextGap(0);
        lblHistory_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistory_mainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHistory_mainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHistory_mainMouseExited(evt);
            }
        });
        getContentPane().add(lblHistory_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 120, 40));

        lblTopSplit.setBackground(new java.awt.Color(3, 1, 54));
        lblTopSplit.setOpaque(true);
        getContentPane().add(lblTopSplit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, 10));

        lblTopPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/panelBackground.jpg"))); // NOI18N
        lblTopPanel.setName(""); // NOI18N
        getContentPane().add(lblTopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 830, 90));

        lblStatus_main.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        lblStatus_main.setForeground(new java.awt.Color(250, 250, 250));
        lblStatus_main.setText(bundle.getString("MainView.lblStatus_main.text")); // NOI18N
        getContentPane().add(lblStatus_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        fldStatus.setEditable(false);
        fldStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fldStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldStatus.setText(bundle.getString("MainView.fldStatus.text")); // NOI18N
        getContentPane().add(fldStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 260, -1));

        lblTime_main.setFont(new java.awt.Font("DS-Digital", 1, 24)); // NOI18N
        lblTime_main.setForeground(new java.awt.Color(250, 250, 250));
        lblTime_main.setText(bundle.getString("MainView.lblTime_main.text")); // NOI18N
        getContentPane().add(lblTime_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        lblDate_main.setFont(new java.awt.Font("DS-Digital", 1, 24)); // NOI18N
        lblDate_main.setForeground(new java.awt.Color(250, 250, 250));
        lblDate_main.setText(bundle.getString("MainView.lblDate_main.text")); // NOI18N
        getContentPane().add(lblDate_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, -1));

        lblBottomSplit.setBackground(new java.awt.Color(3, 1, 54));
        lblBottomSplit.setOpaque(true);
        getContentPane().add(lblBottomSplit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 830, 6));

        lblBottomPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/panelBackground.jpg"))); // NOI18N
        getContentPane().add(lblBottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 830, 50));

        pnlMainPageP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMainTitleP1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMainTitleP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitleP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lblBackground3.png"))); // NOI18N
        lblMainTitleP1.setText(bundle.getString("MainView.lblMainTitleP1.text")); // NOI18N
        lblMainTitleP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblMainTitleP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMainPageP1.add(lblMainTitleP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 860, 40));

        lblRecentDownloadsP1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblRecentDownloadsP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecentDownloadsP1.setText(bundle.getString("MainView.lblRecentDownloadsP1.text")); // NOI18N
        lblRecentDownloadsP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMainPageP1.add(lblRecentDownloadsP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 800, 40));

        btnDetailP1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDetailP1.setText(bundle.getString("MainView.btnDetailP1.text")); // NOI18N
        btnDetailP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 200, 0), 2));
        btnDetailP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailP1MouseClicked(evt);
            }
        });
        pnlMainPageP1.add(btnDetailP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 250, 30));

        tblDownloadsP1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Odkiaľ", "Kam", "Veľkosť", "Stiahnuté", "Stav", "Dátum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollP1.setViewportView(tblDownloadsP1);

        pnlMainPageP1.add(scrollP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 800, 130));

        lblNameP1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblNameP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNameP1.setText(bundle.getString("MainView.lblNameP1.text")); // NOI18N
        lblNameP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMainPageP1.add(lblNameP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 30));

        fldNameP1.setEditable(false);
        fldNameP1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldNameP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldNameP1.setText(bundle.getString("MainView.fldNameP1.text")); // NOI18N
        fldNameP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldNameP1ActionPerformed(evt);
            }
        });
        pnlMainPageP1.add(fldNameP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 240, 30));

        fldSubjectP1.setEditable(false);
        fldSubjectP1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldSubjectP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldSubjectP1.setText(bundle.getString("MainView.fldSubjectP1.text")); // NOI18N
        fldSubjectP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSubjectP1ActionPerformed(evt);
            }
        });
        pnlMainPageP1.add(fldSubjectP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 240, 30));

        lblSubjectP1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblSubjectP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubjectP1.setText(bundle.getString("MainView.lblSubjectP1.text")); // NOI18N
        lblSubjectP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMainPageP1.add(lblSubjectP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, 30));

        fldCreatorsP1.setEditable(false);
        fldCreatorsP1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldCreatorsP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldCreatorsP1.setText(bundle.getString("MainView.fldCreatorsP1.text")); // NOI18N
        fldCreatorsP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldCreatorsP1ActionPerformed(evt);
            }
        });
        pnlMainPageP1.add(fldCreatorsP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 260, 30));

        lblLanguageP1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblLanguageP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLanguageP1.setText(bundle.getString("MainView.lblLanguageP1.text")); // NOI18N
        lblLanguageP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMainPageP1.add(lblLanguageP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 110, 30));

        btnSlovakP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/slovakFlag.jpg"))); // NOI18N
        btnSlovakP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 2));
        btnSlovakP1.setEnabled(false);
        btnSlovakP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSlovakP1MouseClicked(evt);
            }
        });
        btnSlovakP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlovakP1ActionPerformed(evt);
            }
        });
        pnlMainPageP1.add(btnSlovakP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 100, -1));

        btnEnglishP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flagUK.jpg"))); // NOI18N
        btnEnglishP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 2));
        btnEnglishP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnglishP1MouseClicked(evt);
            }
        });
        pnlMainPageP1.add(btnEnglishP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 100, 40));

        lblCreatorsP1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblCreatorsP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCreatorsP1.setText(bundle.getString("MainView.lblCreatorsP1.text")); // NOI18N
        lblCreatorsP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMainPageP1.add(lblCreatorsP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 110, 30));

        btnOpenP1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOpenP1.setText(bundle.getString("MainView.btnOpenP1.text")); // NOI18N
        btnOpenP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 200, 0), 2));
        btnOpenP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenP1MouseClicked(evt);
            }
        });
        pnlMainPageP1.add(btnOpenP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 250, 30));

        lblBackgroundP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        lblBackgroundP1.setInheritsPopupMenu(false);
        lblBackgroundP1.setMaximumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP1.setMinimumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP1.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlMainPageP1.add(lblBackgroundP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 840, 510));

        tabbs.addTab(bundle.getString("MainView.pnlMainPageP1.TabConstraints.tabTitle"), pnlMainPageP1); // NOI18N

        pnlNewDownloadP2.setPreferredSize(new java.awt.Dimension(826, 522));
        pnlNewDownloadP2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fldLocationP2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldLocationP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldLocationP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlNewDownloadP2.add(fldLocationP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 460, 30));

        fldURLP2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldURLP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldURLP2.setText(bundle.getString("MainView.fldURLP2.text")); // NOI18N
        fldURLP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlNewDownloadP2.add(fldURLP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 630, 30));

        btnChooseLocationP2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChooseLocationP2.setText(bundle.getString("MainView.btnChooseLocationP2.text")); // NOI18N
        btnChooseLocationP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChooseLocationP2MouseReleased(evt);
            }
        });
        pnlNewDownloadP2.add(btnChooseLocationP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 160, 30));

        lblMainTitleP2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMainTitleP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitleP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lblBackground2.jpg"))); // NOI18N
        lblMainTitleP2.setText(bundle.getString("MainView.lblMainTitleP2.text")); // NOI18N
        lblMainTitleP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblMainTitleP2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlNewDownloadP2.add(lblMainTitleP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 860, 40));

        lblDestination_P2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDestination_P2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDestination_P2.setText(bundle.getString("MainView.lblDestination_P2.text_1")); // NOI18N
        lblDestination_P2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlNewDownloadP2.add(lblDestination_P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 30));

        lblSource_P2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSource_P2.setText(bundle.getString("MainView.lblSource_P2.text")); // NOI18N
        pnlNewDownloadP2.add(lblSource_P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, 30));

        lblSpaceP2.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblSpaceP2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSpaceP2.setText(bundle.getString("MainView.lblSpaceP2.text")); // NOI18N
        lblSpaceP2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlNewDownloadP2.add(lblSpaceP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 170, 30));

        fldSpaceP2.setEditable(false);
        fldSpaceP2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        fldSpaceP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldSpaceP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSpaceP2ActionPerformed(evt);
            }
        });
        pnlNewDownloadP2.add(fldSpaceP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 230, 30));

        lblSizeP2.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblSizeP2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSizeP2.setText(bundle.getString("MainView.lblSizeP2.text")); // NOI18N
        lblSizeP2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlNewDownloadP2.add(lblSizeP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 180, 30));

        fldSizeP2.setEditable(false);
        fldSizeP2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        fldSizeP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldSizeP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSizeP2ActionPerformed(evt);
            }
        });
        pnlNewDownloadP2.add(fldSizeP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 230, 30));

        lblSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        lblSeparator6.setOpaque(true);
        pnlNewDownloadP2.add(lblSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 780, 3));

        btnDownloadP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/downloadButton.png"))); // NOI18N
        btnDownloadP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 204, 113), 2));
        btnDownloadP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDownloadP2MouseReleased(evt);
            }
        });
        pnlNewDownloadP2.add(btnDownloadP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 130, 80));

        lblBackgroundP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        lblBackgroundP2.setInheritsPopupMenu(false);
        lblBackgroundP2.setMaximumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP2.setMinimumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP2.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlNewDownloadP2.add(lblBackgroundP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 840, 510));

        tabbs.addTab(bundle.getString("MainView.pnlNewDownloadP2.TabConstraints.tabTitle"), pnlNewDownloadP2); // NOI18N

        pnlManageDownloadsP3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSourceP3.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblSourceP3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSourceP3.setText(bundle.getString("MainView.lblSourceP3.text")); // NOI18N
        lblSourceP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblSourceP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 30));

        fldSourceP3.setEditable(false);
        fldSourceP3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldSourceP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldSourceP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSourceP3ActionPerformed(evt);
            }
        });
        pnlManageDownloadsP3.add(fldSourceP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 660, 30));

        lblPercentage_P3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        lblPercentage_P3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPercentage_P3.setText(bundle.getString("MainView.lblPercentage_P3.text_1")); // NOI18N
        lblPercentage_P3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPercentage_P3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblPercentage_P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 420, 30));
        pnlManageDownloadsP3.add(progressBarP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 420, 30));

        tblDownloadsP3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Odkiaľ", "Kam", "Veľkosť", "Stiahnuté", "Stav", "Dátum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDownloadsP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDownloadsP3MouseClicked(evt);
            }
        });
        scrollP3.setViewportView(tblDownloadsP3);

        pnlManageDownloadsP3.add(scrollP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 800, 120));

        btnPauseP3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPauseP3.setText(bundle.getString("MainView.btnPauseP3.text")); // NOI18N
        btnPauseP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 3, 252), 2));
        btnPauseP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPauseP3MouseClicked(evt);
            }
        });
        pnlManageDownloadsP3.add(btnPauseP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 110, 30));

        btnResumeP3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnResumeP3.setText(bundle.getString("MainView.btnResumeP3.text")); // NOI18N
        btnResumeP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 184, 9), 2));
        btnResumeP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResumeP3MouseClicked(evt);
            }
        });
        pnlManageDownloadsP3.add(btnResumeP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 110, 30));

        btnAbortP3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAbortP3.setText(bundle.getString("MainView.btnAbortP3.text")); // NOI18N
        btnAbortP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 3, 3), 2));
        btnAbortP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbortP3MouseClicked(evt);
            }
        });
        pnlManageDownloadsP3.add(btnAbortP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 110, 30));

        lblMainTitleP3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMainTitleP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitleP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lblBackground.jpg"))); // NOI18N
        lblMainTitleP3.setText(bundle.getString("MainView.lblMainTitleP3.text")); // NOI18N
        lblMainTitleP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblMainTitleP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblMainTitleP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 860, 40));

        fldStartP3.setEditable(false);
        fldStartP3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldStartP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldStartP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldStartP3ActionPerformed(evt);
            }
        });
        pnlManageDownloadsP3.add(fldStartP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 250, 30));

        lblStartP3.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblStartP3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStartP3.setText(bundle.getString("MainView.lblStartP3.text")); // NOI18N
        lblStartP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblStartP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 190, 30));

        fldDurationP3.setEditable(false);
        fldDurationP3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldDurationP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldDurationP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldDurationP3ActionPerformed(evt);
            }
        });
        pnlManageDownloadsP3.add(fldDurationP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 150, 30));

        lblDurationP3.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblDurationP3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDurationP3.setText(bundle.getString("MainView.lblDurationP3.text")); // NOI18N
        lblDurationP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblDurationP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 190, 30));

        fldRemainingP3.setEditable(false);
        fldRemainingP3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldRemainingP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldRemainingP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldRemainingP3ActionPerformed(evt);
            }
        });
        pnlManageDownloadsP3.add(fldRemainingP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 150, 30));

        lblRemainingP3.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblRemainingP3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRemainingP3.setText(bundle.getString("MainView.lblRemainingP3.text")); // NOI18N
        lblRemainingP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblRemainingP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 190, 30));

        lblDestinationP3.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblDestinationP3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDestinationP3.setText(bundle.getString("MainView.lblDestinationP3.text")); // NOI18N
        lblDestinationP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblDestinationP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 30));

        fldDestinationP3.setEditable(false);
        fldDestinationP3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldDestinationP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldDestinationP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldDestinationP3ActionPerformed(evt);
            }
        });
        pnlManageDownloadsP3.add(fldDestinationP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 300, 30));

        lblSizeP3.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblSizeP3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSizeP3.setText(bundle.getString("MainView.lblSizeP3.text")); // NOI18N
        lblSizeP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblSizeP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 190, 30));

        fldSizeP3.setEditable(false);
        fldSizeP3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldSizeP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldSizeP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSizeP3ActionPerformed(evt);
            }
        });
        pnlManageDownloadsP3.add(fldSizeP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 210, 30));

        lblStatusP3.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblStatusP3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStatusP3.setText(bundle.getString("MainView.lblStatusP3.text")); // NOI18N
        lblStatusP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlManageDownloadsP3.add(lblStatusP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 190, 30));

        fldStatusP3.setEditable(false);
        fldStatusP3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fldStatusP3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldStatusP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldStatusP3ActionPerformed(evt);
            }
        });
        pnlManageDownloadsP3.add(fldStatusP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 210, 30));

        lblBackgroundP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        lblBackgroundP3.setInheritsPopupMenu(false);
        lblBackgroundP3.setMaximumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP3.setMinimumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP3.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlManageDownloadsP3.add(lblBackgroundP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 840, 510));

        tabbs.addTab(bundle.getString("MainView.pnlManageDownloadsP3.TabConstraints.tabTitle"), pnlManageDownloadsP3); // NOI18N

        pnlUnzipP4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMainTitleP4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMainTitleP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitleP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lblBackground4.jpg"))); // NOI18N
        lblMainTitleP4.setText(bundle.getString("MainView.lblMainTitleP4.text")); // NOI18N
        lblMainTitleP4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblMainTitleP4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlUnzipP4.add(lblMainTitleP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 860, 40));

        btnUnzipP4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUnzipP4.setText(bundle.getString("MainView.btnUnzipP4.text")); // NOI18N
        btnUnzipP4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 135, 230), 2));
        btnUnzipP4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnzipP4MouseClicked(evt);
            }
        });
        pnlUnzipP4.add(btnUnzipP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, 30));

        tblDownloadsP4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Odkiaľ", "Kam", "Veľkosť", "Stiahnuté", "Stav", "Dátum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollP4.setViewportView(tblDownloadsP4);

        pnlUnzipP4.add(scrollP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 800, 290));

        lblBackgroundP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        lblBackgroundP4.setInheritsPopupMenu(false);
        lblBackgroundP4.setMaximumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP4.setMinimumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP4.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlUnzipP4.add(lblBackgroundP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 840, 510));

        tabbs.addTab(bundle.getString("MainView.pnlUnzipP4.TabConstraints.tabTitle"), pnlUnzipP4); // NOI18N

        pnlHistoryP5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMainTitleP5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMainTitleP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitleP5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lblBackground6.jpg"))); // NOI18N
        lblMainTitleP5.setText(bundle.getString("MainView.lblMainTitleP5.text")); // NOI18N
        lblMainTitleP5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblMainTitleP5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHistoryP5.add(lblMainTitleP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 860, 40));

        tblDownloadsP5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Odkiaľ", "Kam", "Veľkosť", "Stiahnuté", "Stav", "Dátum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollP5.setViewportView(tblDownloadsP5);

        pnlHistoryP5.add(scrollP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 800, 290));

        btnDetailP5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDetailP5.setText(bundle.getString("MainView.btnDetailP5.text")); // NOI18N
        btnDetailP5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 32, 36), 2));
        btnDetailP5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailP5MouseClicked(evt);
            }
        });
        pnlHistoryP5.add(btnDetailP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 240, 30));

        lblBackgroundP5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        lblBackgroundP5.setInheritsPopupMenu(false);
        lblBackgroundP5.setMaximumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP5.setMinimumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP5.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlHistoryP5.add(lblBackgroundP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 840, 510));

        tabbs.addTab(bundle.getString("MainView.pnlHistoryP5.TabConstraints.tabTitle"), pnlHistoryP5); // NOI18N

        pnlDetailP6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSourceP6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblSourceP6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSourceP6.setText(bundle.getString("MainView.lblSourceP6.text")); // NOI18N
        lblSourceP6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDetailP6.add(lblSourceP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 110, 30));

        lblNameP6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblNameP6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNameP6.setText(bundle.getString("MainView.lblNameP6.text")); // NOI18N
        lblNameP6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDetailP6.add(lblNameP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, 30));

        lblSizeP6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblSizeP6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSizeP6.setText(bundle.getString("MainView.lblSizeP6.text")); // NOI18N
        lblSizeP6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDetailP6.add(lblSizeP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 110, 30));

        fldSizeP6.setEditable(false);
        fldSizeP6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldSizeP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldSizeP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSizeP6ActionPerformed(evt);
            }
        });
        pnlDetailP6.add(fldSizeP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 230, 30));

        fldNameP6.setEditable(false);
        fldNameP6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldNameP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldNameP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldNameP6ActionPerformed(evt);
            }
        });
        pnlDetailP6.add(fldNameP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 710, 30));

        fldSourceP6.setEditable(false);
        fldSourceP6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldSourceP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldSourceP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSourceP6ActionPerformed(evt);
            }
        });
        pnlDetailP6.add(fldSourceP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 710, 30));

        lblDateP6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblDateP6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDateP6.setText(bundle.getString("MainView.lblDateP6.text")); // NOI18N
        lblDateP6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDetailP6.add(lblDateP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 110, 30));

        lblDurationP6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblDurationP6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDurationP6.setText(bundle.getString("MainView.lblDurationP6.text")); // NOI18N
        lblDurationP6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDetailP6.add(lblDurationP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 110, 30));

        fldDurationP6.setEditable(false);
        fldDurationP6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldDurationP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldDurationP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldDurationP6ActionPerformed(evt);
            }
        });
        pnlDetailP6.add(fldDurationP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 230, 30));

        fldDateP6.setEditable(false);
        fldDateP6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldDateP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldDateP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldDateP6ActionPerformed(evt);
            }
        });
        pnlDetailP6.add(fldDateP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 30));

        lblMainTitleP6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMainTitleP6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitleP6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lblBackground5.jpg"))); // NOI18N
        lblMainTitleP6.setText(bundle.getString("MainView.lblMainTitleP6.text")); // NOI18N
        lblMainTitleP6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblMainTitleP6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDetailP6.add(lblMainTitleP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 860, 50));

        fldStatusP6.setEditable(false);
        fldStatusP6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fldStatusP6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldStatusP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldStatusP6ActionPerformed(evt);
            }
        });
        pnlDetailP6.add(fldStatusP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 230, 30));

        lblStatusP6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblStatusP6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStatusP6.setText(bundle.getString("MainView.lblStatusP6.text")); // NOI18N
        lblStatusP6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDetailP6.add(lblStatusP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 110, 30));

        btnOpenP6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOpenP6.setText(bundle.getString("MainView.btnOpenP6.text")); // NOI18N
        btnOpenP6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        btnOpenP6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenP6MouseClicked(evt);
            }
        });
        pnlDetailP6.add(btnOpenP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 270, 30));

        lblBackgroundP6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        lblBackgroundP6.setInheritsPopupMenu(false);
        lblBackgroundP6.setMaximumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP6.setMinimumSize(new java.awt.Dimension(800, 600));
        lblBackgroundP6.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlDetailP6.add(lblBackgroundP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 840, 510));

        lblTempP6.setText(bundle.getString("MainView.lblTempP6.text")); // NOI18N
        pnlDetailP6.add(lblTempP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        tabbs.addTab(bundle.getString("MainView.pnlDetailP6.TabConstraints.tabTitle"), pnlDetailP6); // NOI18N

        getContentPane().add(tabbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseLocationP2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseLocationP2MouseReleased
        try {
            String urlString1 = fldURLP2.getText();
            String pathString1 = DestinationResolver.getDownloadPath(urlString1);
            fldLocationP2.setText(pathString1);
            
            fldSpaceP2.setText(downloadController.getFreeSpace());
            fldSizeP2.setText(downloadController.getFileSize(urlString1));
            
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nesprávna URL adresa");
        } catch (NoFileSelected ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChooseLocationP2MouseReleased

    private void lblMain_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMain_mainMouseClicked
        switchPanel(lblMain_main, 0);
    }//GEN-LAST:event_lblMain_mainMouseClicked

    private void lblNewDownload_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewDownload_mainMouseClicked
        switchPanel(lblNewDownload_main, 1);
    }//GEN-LAST:event_lblNewDownload_mainMouseClicked

    private void lblManageDownloads_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageDownloads_mainMouseClicked
        switchPanel(lblManageDownloads_main, 2);
    }//GEN-LAST:event_lblManageDownloads_mainMouseClicked

    private void lblUnzip_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnzip_mainMouseClicked
        switchPanel(lblUnzip_main, 3);
    }//GEN-LAST:event_lblUnzip_mainMouseClicked

    private void lblHistory_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistory_mainMouseClicked
        switchPanel(lblHistory_main, 4);
    }//GEN-LAST:event_lblHistory_mainMouseClicked

    private void lblMain_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMain_mainMouseEntered
        lblMain_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 3));
    }//GEN-LAST:event_lblMain_mainMouseEntered

    private void lblNewDownload_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewDownload_mainMouseEntered
        lblNewDownload_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 3));
    }//GEN-LAST:event_lblNewDownload_mainMouseEntered

    private void lblManageDownloads_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageDownloads_mainMouseEntered
        lblManageDownloads_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 3));
    }//GEN-LAST:event_lblManageDownloads_mainMouseEntered

    private void lblUnzip_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnzip_mainMouseEntered
        lblUnzip_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 3));
    }//GEN-LAST:event_lblUnzip_mainMouseEntered

    private void lblHistory_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistory_mainMouseEntered
        lblHistory_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 3));
    }//GEN-LAST:event_lblHistory_mainMouseEntered

    private void lblMain_mainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMain_mainMouseExited
        if (lblMain_main.equals(lblActualPanel) == false)
            lblMain_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
    }//GEN-LAST:event_lblMain_mainMouseExited

    private void lblNewDownload_mainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewDownload_mainMouseExited
        if (lblNewDownload_main.equals(lblActualPanel) == false)
            lblNewDownload_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
    }//GEN-LAST:event_lblNewDownload_mainMouseExited

    private void lblManageDownloads_mainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageDownloads_mainMouseExited
        if (lblManageDownloads_main.equals(lblActualPanel) == false)
            lblManageDownloads_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
    }//GEN-LAST:event_lblManageDownloads_mainMouseExited

    private void lblUnzip_mainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnzip_mainMouseExited
        if (lblUnzip_main.equals(lblActualPanel) == false)
            lblUnzip_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
    }//GEN-LAST:event_lblUnzip_mainMouseExited

    private void lblHistory_mainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistory_mainMouseExited
        if (lblHistory_main.equals(lblActualPanel) == false)
            lblHistory_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
    }//GEN-LAST:event_lblHistory_mainMouseExited

    private void fldSourceP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSourceP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSourceP3ActionPerformed

    private void fldStartP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldStartP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldStartP3ActionPerformed

    private void fldDurationP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldDurationP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldDurationP3ActionPerformed

    private void fldRemainingP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldRemainingP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldRemainingP3ActionPerformed

    private void fldDestinationP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldDestinationP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldDestinationP3ActionPerformed

    private void fldSizeP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSizeP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSizeP3ActionPerformed

    private void fldStatusP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldStatusP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldStatusP3ActionPerformed

    private void fldSpaceP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSpaceP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSpaceP2ActionPerformed

    private void fldSizeP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSizeP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSizeP2ActionPerformed

    private void fldSizeP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSizeP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSizeP6ActionPerformed

    private void fldNameP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldNameP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldNameP6ActionPerformed

    private void fldSourceP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSourceP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSourceP6ActionPerformed

    private void fldDurationP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldDurationP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldDurationP6ActionPerformed

    private void fldDateP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldDateP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldDateP6ActionPerformed

    private void fldStatusP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldStatusP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldStatusP6ActionPerformed

    private void fldNameP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldNameP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldNameP1ActionPerformed

    private void fldSubjectP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSubjectP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSubjectP1ActionPerformed

    private void fldCreatorsP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldCreatorsP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldCreatorsP1ActionPerformed

    private void btnSlovakP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlovakP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSlovakP1ActionPerformed

    private void btnDetailP5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailP5MouseClicked
        // TODO add your handling code here:
        int selectedTableIndex = tblDownloadsP5.getSelectedRow();
        if(selectedTableIndex >= 0){
            this.fldNameP6.setText(this.recordController.getSpecificDestination(selectedTableIndex));
            this.fldSourceP6.setText(this.recordController.getSpecificSource(selectedTableIndex));
            this.fldSizeP6.setText(this.recordController.getSpecificSize(selectedTableIndex));
            this.fldDateP6.setText(this.recordController.getSpecificDate(selectedTableIndex));
            this.fldStatusP6.setText(this.recordController.getSpecificStatus(selectedTableIndex));
            this.fldDurationP6.setText(this.recordController.getSpecificTime(selectedTableIndex));
            switchPanel(lblTempP6, 5);
        } else{
            JOptionPane.showMessageDialog(lblBottomPanel, "Vyberte zaznam");
        }
    }//GEN-LAST:event_btnDetailP5MouseClicked

    private void btnOpenP6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenP6MouseClicked
        try {
            this.recordController.openFileLoacation(fldNameP6.getText());
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOpenP6MouseClicked

    private void btnPauseP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPauseP3MouseClicked
        try {
            this.downloadController.pauseDownloading();
        } catch (InterruptedException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPauseP3MouseClicked

    private void tblDownloadsP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDownloadsP3MouseClicked
        
        int selectedIndex = tblDownloadsP3.getSelectedRow();
        if(selectedIndex < 0){
            return;
        }
        downloadController.setUpIndex(selectedIndex);
        downloadController.startProgressChecker();
    }//GEN-LAST:event_tblDownloadsP3MouseClicked

    private void btnResumeP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResumeP3MouseClicked
        try {
            this.downloadController.resumeDownloading();
        } catch (InterruptedException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResumeP3MouseClicked

    private void btnAbortP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbortP3MouseClicked
        this.downloadController.cancelDownloading();
    }//GEN-LAST:event_btnAbortP3MouseClicked

    private void btnEnglishP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnglishP1MouseClicked
        this.switchToEnglish();
    }//GEN-LAST:event_btnEnglishP1MouseClicked

    private void btnSlovakP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSlovakP1MouseClicked
        this.switchToSlovak();
    }//GEN-LAST:event_btnSlovakP1MouseClicked

    private void btnDownloadP2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDownloadP2MouseReleased
        try {
            String urlString1 = fldURLP2.getText();
            String pathString1 = fldLocationP2.getText();
            
            fldURLP2.setText("URL");
            fldLocationP2.setText("");
            fldSpaceP2.setText("");
            fldSizeP2.setText("");
            
            this.downloadController.download(urlString1, pathString1);
            
            switchPanel(lblManageDownloads_main, 2);
            
        } catch (MalformedURLException | InvalidUrlException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nesprávna URL adresa");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "IO chybicka");
        }
    }//GEN-LAST:event_btnDownloadP2MouseReleased

    private void btnUnzipP4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnzipP4MouseClicked
        // TODO add your handling code here:
        int selectedZipIndex = tblDownloadsP4.getSelectedRow();
        if(selectedZipIndex >= 0){
            try {
                recordController.unzipFile(selectedZipIndex);
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotZipException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoFileSelected ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUnzipP4MouseClicked

    private void btnOpenP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenP1MouseClicked
        // TODO add your handling code here:
        int selectedIndex = tblDownloadsP1.getSelectedRow();
        if(selectedIndex >= 0){
            try {
                recordController.openFileLoacation(selectedIndex);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(lblBottomPanel, "Subor bol premiestneny alebo odstraneny");
            }
        }
        
    }//GEN-LAST:event_btnOpenP1MouseClicked

    private void btnDetailP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailP1MouseClicked
        // TODO add your handling code here:
        int selectedTableIndex = tblDownloadsP1.getSelectedRow();
        if(selectedTableIndex >= 0){
            this.fldNameP6.setText(this.recordController.getSpecificDestination(selectedTableIndex));
            this.fldSourceP6.setText(this.recordController.getSpecificSource(selectedTableIndex));
            this.fldSizeP6.setText(this.recordController.getSpecificSize(selectedTableIndex));
            this.fldDateP6.setText(this.recordController.getSpecificDate(selectedTableIndex));
            this.fldStatusP6.setText(this.recordController.getSpecificStatus(selectedTableIndex));
            this.fldDurationP6.setText(this.recordController.getSpecificTime(selectedTableIndex));
            switchPanel(lblTempP6, 5);
        } else{
            JOptionPane.showMessageDialog(lblBottomPanel, "Vyberte zaznam");
        }
    }//GEN-LAST:event_btnDetailP1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbortP3;
    private javax.swing.JButton btnChooseLocationP2;
    private javax.swing.JButton btnDetailP1;
    private javax.swing.JButton btnDetailP5;
    private javax.swing.JButton btnDownloadP2;
    private javax.swing.JButton btnEnglishP1;
    private javax.swing.JButton btnOpenP1;
    private javax.swing.JButton btnOpenP6;
    private javax.swing.JButton btnPauseP3;
    private javax.swing.JButton btnResumeP3;
    private javax.swing.JButton btnSlovakP1;
    private javax.swing.JButton btnUnzipP4;
    private javax.swing.JTextField fldCreatorsP1;
    private javax.swing.JTextField fldDateP6;
    private javax.swing.JTextField fldDestinationP3;
    private javax.swing.JTextField fldDurationP3;
    private javax.swing.JTextField fldDurationP6;
    private javax.swing.JTextField fldLocationP2;
    private javax.swing.JTextField fldNameP1;
    private javax.swing.JTextField fldNameP6;
    private javax.swing.JTextField fldRemainingP3;
    private javax.swing.JTextField fldSizeP2;
    private javax.swing.JTextField fldSizeP3;
    private javax.swing.JTextField fldSizeP6;
    private javax.swing.JTextField fldSourceP3;
    private javax.swing.JTextField fldSourceP6;
    private javax.swing.JTextField fldSpaceP2;
    private javax.swing.JTextField fldStartP3;
    private javax.swing.JTextField fldStatus;
    private javax.swing.JTextField fldStatusP3;
    private javax.swing.JTextField fldStatusP6;
    private javax.swing.JTextField fldSubjectP1;
    private javax.swing.JTextField fldURLP2;
    private javax.swing.JLabel lblBackgroundP1;
    private javax.swing.JLabel lblBackgroundP2;
    private javax.swing.JLabel lblBackgroundP3;
    private javax.swing.JLabel lblBackgroundP4;
    private javax.swing.JLabel lblBackgroundP5;
    private javax.swing.JLabel lblBackgroundP6;
    private javax.swing.JLabel lblBottomPanel;
    private javax.swing.JLabel lblBottomSplit;
    private javax.swing.JLabel lblCreatorsP1;
    private javax.swing.JLabel lblDateP6;
    private javax.swing.JLabel lblDate_main;
    private javax.swing.JLabel lblDestinationP3;
    private javax.swing.JLabel lblDestination_P2;
    private javax.swing.JLabel lblDurationP3;
    private javax.swing.JLabel lblDurationP6;
    private javax.swing.JLabel lblHistory_main;
    private javax.swing.JLabel lblLanguageP1;
    private javax.swing.JLabel lblMainTitleP1;
    private javax.swing.JLabel lblMainTitleP2;
    private javax.swing.JLabel lblMainTitleP3;
    private javax.swing.JLabel lblMainTitleP4;
    private javax.swing.JLabel lblMainTitleP5;
    private javax.swing.JLabel lblMainTitleP6;
    private javax.swing.JLabel lblMain_main;
    private javax.swing.JLabel lblManageDownloads_main;
    private javax.swing.JLabel lblNameP1;
    private javax.swing.JLabel lblNameP6;
    private javax.swing.JLabel lblNewDownload_main;
    private javax.swing.JLabel lblPercentage_P3;
    private javax.swing.JLabel lblRecentDownloadsP1;
    private javax.swing.JLabel lblRemainingP3;
    private javax.swing.JLabel lblSeparator6;
    private javax.swing.JLabel lblSizeP2;
    private javax.swing.JLabel lblSizeP3;
    private javax.swing.JLabel lblSizeP6;
    private javax.swing.JLabel lblSourceP3;
    private javax.swing.JLabel lblSourceP6;
    private javax.swing.JLabel lblSource_P2;
    private javax.swing.JLabel lblSpaceP2;
    private javax.swing.JLabel lblStartP3;
    private javax.swing.JLabel lblStatusP3;
    private javax.swing.JLabel lblStatusP6;
    private javax.swing.JLabel lblStatus_main;
    private javax.swing.JLabel lblSubjectP1;
    private javax.swing.JLabel lblTempP6;
    private javax.swing.JLabel lblTime_main;
    private javax.swing.JLabel lblTopPanel;
    private javax.swing.JLabel lblTopSplit;
    private javax.swing.JLabel lblUnzip_main;
    private javax.swing.JPanel pnlDetailP6;
    private javax.swing.JPanel pnlHistoryP5;
    private javax.swing.JPanel pnlMainPageP1;
    private javax.swing.JPanel pnlManageDownloadsP3;
    private javax.swing.JPanel pnlNewDownloadP2;
    private javax.swing.JPanel pnlUnzipP4;
    private javax.swing.JProgressBar progressBarP3;
    private javax.swing.JScrollPane scrollP1;
    private javax.swing.JScrollPane scrollP3;
    private javax.swing.JScrollPane scrollP4;
    private javax.swing.JScrollPane scrollP5;
    private javax.swing.JTabbedPane tabbs;
    private javax.swing.JTable tblDownloadsP1;
    private javax.swing.JTable tblDownloadsP3;
    private javax.swing.JTable tblDownloadsP4;
    private javax.swing.JTable tblDownloadsP5;
    // End of variables declaration//GEN-END:variables
    
    
    /**
     * Used to switch between Panels in JFrame
     * @param lblActual label to be highlighted
     * @param switchTo int panel number
     */
    public void switchPanel(JLabel lblActual, int switchTo){
        this.lblActualPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 1, 54), 3));
        lblActual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 245, 255), 3));
        this.lblActualPanel = lblActual;
        tabbs.setSelectedIndex(switchTo);
    }
    
    /**
     * Switch table contents according to actual language selected
     */
    public void updateTables(){
        if(!btnSlovakP1.isEnabled()){
            tblDownloadsP1.setModel(recordController.getRecent());
            try {
                tblDownloadsP4.setModel(recordController.getDownloadedZips());
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
            tblDownloadsP5.setModel(recordController.getDownloaded());
        } else{
            tblDownloadsP1.setModel(recordController.getRecentEnglish());
            try {
                tblDownloadsP4.setModel(recordController.getDownloadedZipsEnglish());
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
            tblDownloadsP5.setModel(recordController.getDownloadedEnglish());
        }
    }
    
    /**
     * Used to refresh table in Panel 3
     */
    public void displayDownloadTable(){
        if(!btnSlovakP1.isEnabled()){
            tblDownloadsP3.setModel(downloadController.getDownloading());
        } else{
            tblDownloadsP3.setModel(downloadController.getDownloadingEnglish());
        }
    }

    /**
     * Displaying current state of application
     */
    public void displayState() {
        if(!btnSlovakP1.isEnabled()){
            this.fldStatus.setText(this.downloadController.getProgramStatus());
        }
        else{
           this.fldStatus.setText(this.downloadController.getProgramStatusEnglish()); 
        }
    }
    
    /**
     * Show detailed information about download
     */
    public void showDownloadDetail(){
        fldSourceP3.setText(downloadController.getDownloadingSource());
        fldDestinationP3.setText(downloadController.getDownloadingDest());
        fldSizeP3.setText(downloadController.getDownloadingSize());
        fldStatusP3.setText(downloadController.getDownloadingStatus());
        fldStartP3.setText(downloadController.getDownloadingStart());
        fldDurationP3.setText(downloadController.getDownloadingTime());
        fldRemainingP3.setText(downloadController.getEstimatedTime());
        lblPercentage_P3.setText(downloadController.getPercentage());
        progressBarP3.setMaximum((int) downloadController.getTotalSize());
        progressBarP3.setValue((int) downloadController.getDownloadedSize());
    }
    
    /**
     * Switch application to Slovak language
     */
    public void switchToSlovak(){
        btnSlovakP1.setEnabled(false);
        btnEnglishP1.setEnabled(true);
        
        Locale l = new Locale("sk", "SK");
        ResourceBundle r = ResourceBundle.getBundle("sk.stu.fiit.views/Bundle", l);
        
        btnUnzipP4.setText(r.getString("MainView.btnUnzipP4.text"));
        lblMainTitleP4.setText(r.getString("MainView.lblMainTitleP4.text"));
        lblStatusP3.setText(r.getString("MainView.lblStatusP3.text"));
        lblSizeP3.setText(r.getString("MainView.lblSizeP3.text"));
        btnOpenP6.setText(r.getString("MainView.btnOpenP6.text"));
        lblStatusP6.setText(r.getString("MainView.lblStatusP6.text"));
        lblMainTitleP6.setText(r.getString("MainView.lblMainTitleP6.text"));
        lblDestinationP3.setText(r.getString("MainView.lblDestinationP3.text"));
        lblRemainingP3.setText(r.getString("MainView.lblRemainingP3.text"));
        lblDurationP3.setText(r.getString("MainView.lblDurationP3.text"));
        lblStartP3.setText(r.getString("MainView.lblStartP3.text"));
        lblMainTitleP3.setText(r.getString("MainView.lblMainTitleP3.text"));
        btnAbortP3.setText(r.getString("MainView.btnAbortP3.text"));
        lblDurationP6.setText(r.getString("MainView.lblDurationP6.text"));
        lblDateP6.setText(r.getString("MainView.lblDateP6.text"));
        lblSizeP6.setText(r.getString("MainView.lblSizeP6.text"));
        lblNameP6.setText(r.getString("MainView.lblNameP6.text"));
        lblSourceP6.setText(r.getString("MainView.lblSourceP6.text"));
        btnResumeP3.setText(r.getString("MainView.btnResumeP3.text"));
        btnPauseP3.setText(r.getString("MainView.btnPauseP3.text"));
        lblSourceP3.setText(r.getString("MainView.lblSourceP3.text"));
        lblMainTitleP2.setText(r.getString("MainView.lblMainTitleP2.text"));
        btnOpenP1.setText(r.getString("MainView.btnOpenP1.text"));
        lblCreatorsP1.setText(r.getString("MainView.lblCreatorsP1.text"));
        lblLanguageP1.setText(r.getString("MainView.lblLanguageP1.text"));
        lblSubjectP1.setText(r.getString("MainView.lblSubjectP1.text"));
        fldNameP1.setText(r.getString("MainView.fldNameP1.text"));
        lblNameP1.setText(r.getString("MainView.lblNameP1.text"));
        btnDetailP1.setText(r.getString("MainView.btnDetailP1.text"));
        lblRecentDownloadsP1.setText(r.getString("MainView.lblRecentDownloadsP1.text"));
        btnDetailP5.setText(r.getString("MainView.btnDetailP5.text"));
        lblMainTitleP5.setText(r.getString("MainView.lblMainTitleP5.text"));
        btnChooseLocationP2.setText(r.getString("MainView.btnChooseLocationP2.text"));
        lblSizeP2.setText(r.getString("MainView.lblSizeP2.text"));
        lblSpaceP2.setText(r.getString("MainView.lblSpaceP2.text"));
        fldURLP2.setText(r.getString("MainView.fldURLP2.text"));
        lblStatus_main.setText(r.getString("MainView.lblStatus_main.text"));
        lblMain_main.setText(r.getString("MainView.lblMain_main.text"));
        lblNewDownload_main.setText(r.getString("MainView.lblNewDownload_main.text_1"));
        lblManageDownloads_main.setText(r.getString("MainView.lblManageDownloads_main.text_1"));
        lblUnzip_main.setText(r.getString("MainView.lblUnzip_main.text_1"));
        lblHistory_main.setText(r.getString("MainView.lblHistory_main.text_1"));
        lblSource_P2.setText(r.getString("MainView.lblSource_P2.text"));
        lblPercentage_P3.setText(r.getString("MainView.lblPercentage_P3.text_1"));
        lblDestination_P2.setText(r.getString("MainView.lblDestination_P2.text_1"));
        
        updateTables();
    }
    
    
    /**
     * Stich application to English language
     */
    public void switchToEnglish(){
        btnSlovakP1.setEnabled(true);
        btnEnglishP1.setEnabled(false);
        
        Locale l = new Locale("en", "GB");
        ResourceBundle r = ResourceBundle.getBundle("sk.stu.fiit.views/Bundle_en_GB", l);
        
        btnUnzipP4.setText(r.getString("MainView.btnUnzipP4.text"));
        lblMainTitleP4.setText(r.getString("MainView.lblMainTitleP4.text"));
        lblStatusP3.setText(r.getString("MainView.lblStatusP3.text"));
        lblSizeP3.setText(r.getString("MainView.lblSizeP3.text"));
        btnOpenP6.setText(r.getString("MainView.btnOpenP6.text"));
        lblStatusP6.setText(r.getString("MainView.lblStatusP6.text"));
        lblMainTitleP6.setText(r.getString("MainView.lblMainTitleP6.text"));
        lblDestinationP3.setText(r.getString("MainView.lblDestinationP3.text"));
        lblRemainingP3.setText(r.getString("MainView.lblRemainingP3.text"));
        lblDurationP3.setText(r.getString("MainView.lblDurationP3.text"));
        lblStartP3.setText(r.getString("MainView.lblStartP3.text"));
        lblMainTitleP3.setText(r.getString("MainView.lblMainTitleP3.text"));
        btnAbortP3.setText(r.getString("MainView.btnAbortP3.text"));
        lblDurationP6.setText(r.getString("MainView.lblDurationP6.text"));
        lblDateP6.setText(r.getString("MainView.lblDateP6.text"));
        lblSizeP6.setText(r.getString("MainView.lblSizeP6.text"));
        lblNameP6.setText(r.getString("MainView.lblNameP6.text"));
        lblSourceP6.setText(r.getString("MainView.lblSourceP6.text"));
        btnResumeP3.setText(r.getString("MainView.btnResumeP3.text"));
        btnPauseP3.setText(r.getString("MainView.btnPauseP3.text"));
        lblSourceP3.setText(r.getString("MainView.lblSourceP3.text"));
        lblMainTitleP2.setText(r.getString("MainView.lblMainTitleP2.text"));
        btnOpenP1.setText(r.getString("MainView.btnOpenP1.text"));
        lblCreatorsP1.setText(r.getString("MainView.lblCreatorsP1.text"));
        lblLanguageP1.setText(r.getString("MainView.lblLanguageP1.text"));
        lblSubjectP1.setText(r.getString("MainView.lblSubjectP1.text"));
        fldNameP1.setText(r.getString("MainView.fldNameP1.text"));
        lblNameP1.setText(r.getString("MainView.lblNameP1.text"));
        btnDetailP1.setText(r.getString("MainView.btnDetailP1.text"));
        lblRecentDownloadsP1.setText(r.getString("MainView.lblRecentDownloadsP1.text"));
        btnDetailP5.setText(r.getString("MainView.btnDetailP5.text"));
        lblMainTitleP5.setText(r.getString("MainView.lblMainTitleP5.text"));
        btnChooseLocationP2.setText(r.getString("MainView.btnChooseLocationP2.text"));
        lblSizeP2.setText(r.getString("MainView.lblSizeP2.text"));
        lblSpaceP2.setText(r.getString("MainView.lblSpaceP2.text"));
        fldURLP2.setText(r.getString("MainView.fldURLP2.text"));
        lblStatus_main.setText(r.getString("MainView.lblStatus_main.text"));
        lblMain_main.setText(r.getString("MainView.lblMain_main.text"));
        lblNewDownload_main.setText(r.getString("MainView.lblNewDownload_main.text_1"));
        lblManageDownloads_main.setText(r.getString("MainView.lblManageDownloads_main.text_1"));
        lblUnzip_main.setText(r.getString("MainView.lblUnzip_main.text_1"));
        lblHistory_main.setText(r.getString("MainView.lblHistory_main.text_1"));
        lblSource_P2.setText(r.getString("MainView.lblSource_P2.text"));
        lblPercentage_P3.setText(r.getString("MainView.lblPercentage_P3.text_1"));
        lblDestination_P2.setText(r.getString("MainView.lblDestination_P2.text_1"));
        
        updateTables();
    }
    
    /**
     * Set fields and labels in Panel 3 to empty 
     */
    public void eraseDetailFields(){
        fldSourceP3.setText("");
        fldDestinationP3.setText("");
        fldSizeP3.setText("");
        fldStatusP3.setText("");
        fldStartP3.setText("");
        fldDurationP3.setText("");
        fldRemainingP3.setText("");
        lblPercentage_P3.setText("0%");
        progressBarP3.setValue(0);
        
    }

    /**
     * Handling for closing application
     */
    private void initWindowlistener() {
        this.addWindowListener(new WindowAdapter() { 
            @Override
            public void windowClosing(WindowEvent evt) { 
                int result = JOptionPane.showConfirmDialog(null, "Zavretím aplikácie prerušíte prípadné sťahovania\nAj tak pokračovať?");
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                if(result == JOptionPane.YES_OPTION){
                    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    downloadController.clean();
                    System.exit(0);
                }
                
            } 
        });
    }
}
